name: simmano_kasir_servis
publish_to: 'none'
description: SIMMANO KASIR & SERVIS V1 - offline-first Android app.
version: 1.0.0+1
environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  intl: ^0.20.2
  url_launcher: ^6.3.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/simmano_logo.png
